apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  type: LoadBalancer
  selector:
    app: superset
  ports:
  - name: http
    port: 8088
    targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: amancevice/superset:1.1.0
        env:
          - name: DB_HOST
            value: superset-mysql
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: DB_NAME
            value: "superset"
          - name: REDIS_HOST
            value: superset-redis
          - name: REDIS_PORT
            value: "6379"          
        resources:
          limits:
            memory: "2Gi"
            cpu: "1500m"
        ports:
          - containerPort: 8088
        volumeMounts:
          - mountPath: /home/superset/superset
            name: superset-config
      volumes:
        - name: superset-config
          configMap:
            name: superset-config
